### PR TITLE
Improved the UI of full blog page

### PR DESCRIPTION
**Pull request by bharath090909**
issueno: #43 
Enhanced the full blog page's user interface by introducing icons alongside the 'Like' and 'Add Comment' buttons. Additionally, I optimized the positioning of the title and adjusted the image size."

Screenshot 2023-10-05 at 12 00 56 AM

Screenshot 2023-10-05 at 12 01 08 AM

### CODE REVIEW

**Comment by adityyaa-10** [comment]
@bharath090909 remove the button texts saying 'Go back' and like(0), instead use icons only, 

for likes, try do do when the post is not liked, the icon is white, and after liking it shall turn blue.

**Comment by bharath090909** [comment]
Okay I will do the changes and let you know.

**Comment by bharath090909** [comment]
@adityyaa-10 i have completed the task and send please check them.

**Comment by adityyaa-10** [comment]
Great @bharath090909 I'll see to it and merge your pr. You are free to look for bugs and raise issues till then.

**Pull request merged**
